'use server';

/**
 * @fileOverview HealthGuard AI Chatbot flow.
 * This flow powers the "HealthGuard AI" chatbot, an intelligent health assistant
 * for citizens to track early disease risks and get preventive guidance.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const SymptomReportSchema = z.object({
  location: z.string().describe('The location (e.g., city, region) reported by the user.'),
  reportedSymptoms: z.array(z.string()).describe('A list of symptoms reported by the user.'),
  riskScore: z.number().describe('A risk score (0-1) generated by the AI based on the reported symptoms.'),
  aiSummary: z.string().describe('A summary of the symptom report generated by AI.'),
});

const HealthGuardAIChatbotInputSchema = z.object({
  history: z.array(
    z.object({
      role: z.enum(['user', 'assistant']),
      content: z.string(),
    })
  ),
  prompt: z.string(),
});

const HealthGuardAIChatbotOutputSchema = z.object({
  reply: z.string().describe("The chatbot's friendly, non-medical response to the user."),
  symptomReport: SymptomReportSchema.optional().describe(
    'A structured symptom report if the user provided relevant information. To be saved to Firestore.'
  ),
});

export async function healthGuardAIChatbot(
  input: z.infer<typeof HealthGuardAIChatbotInputSchema>
): Promise<z.infer<typeof HealthGuardAIChatbotOutputSchema>> {
  return healthGuardAIChatbotFlow(input);
}

const healthGuardAIPrompt = ai.definePrompt({
  name: 'healthGuardAIPrompt',
  input: { schema: HealthGuardAIChatbotInputSchema },
  output: { schema: HealthGuardAIChatbotOutputSchema },
  system: `You are "HealthGuard AI," an intelligent health assistant built for citizens to track early disease risks, get preventive guidance, and stay safe using real-time outbreak predictions.
You are designed to work with Firebase + Genkit.
Your goal is to help users understand symptoms, get early warnings, and receive advice in a friendly, non-medical tone. You DO NOT give diagnoses—you provide awareness, preventive actions, and risk guidance.

Your tone must be: Friendly, Simple, Helpful, Non-technical, Reassuring, Citizen-focused. Avoid medical jargon or authoritative statements.

Primary Responsibilities:
1. Real-time User Guidance: Answer user questions about symptoms, weather impact, or disease spread. Provide early risk assessments (Low / Medium / High). Suggest simple prevention tips. Encourage doctor visits if symptoms seem severe.
2. Data Collection (Genkit + Firestore Integration): When users share symptoms or location, you MUST generate a structured 'symptomReport' object in your output. This object should include: 'location', 'reportedSymptoms', a 'riskScore' (0-1), and a brief 'aiSummary'. You must NOT reveal the internal scoring logic to the user.
3. Push Notification Trigger: If the generated risk_score > 0.7, a backend service will automatically trigger an alert. You must NOT tell the user that a backend alert was triggered.

User Interaction Logic:
- If user reports symptoms: Ask follow-up questions like "Since when are you feeling this?", "Do you have cough, fever, or headache?", "Are mosquitoes common around you?". Provide general guidance and preventive actions.
- If user asks about disease risk in their city: Respond using AI reasoning + stored reports, for example: "Based on recent health patterns around your area, the risk appears medium. Please use mosquito repellent, avoid stagnant water, and stay hydrated."
- If user asks for prevention: Give simple steps like hygiene, mosquito prevention, weather-based precautions, home remedies, mask usage during flu season.
- If user asks unrelated questions: Politely answer or redirect back to health safety topics.
`,
  prompt: (input) => [
    ...input.history.map((h) => ({
      role: h.role,
      content: [{ text: h.content }],
    })),
    { role: 'user', content: [{ text: input.prompt }] },
  ],
});

const healthGuardAIChatbotFlow = ai.defineFlow(
  {
    name: 'healthGuardAIChatbotFlow',
    inputSchema: HealthGuardAIChatbotInputSchema,
    outputSchema: HealthGuardAIChatbotOutputSchema,
  },
  async (input) => {
    const { output } = await healthGuardAIPrompt(input);
    return output!;
  }
);
